export const courses = [
  {
    slug: "advanced-python",
    title: "Advanced Python",
    description:
      "Master Python with advanced patterns, async programming, decorators, metaclasses, and performance optimization techniques.",
    duration: "8 weeks",
    level: "Advanced",
    color: "blue",
    price: 799,
    originalPrice: 999,
  },
  {
    slug: "cloud-devops",
    title: "Cloud DevOps",
    description:
      "Learn CI/CD pipelines, Kubernetes, Terraform, Docker, and cloud-native deployment strategies on AWS, Azure, and GCP.",
    duration: "10 weeks",
    level: "Intermediate",
    color: "green",
    price: 899,
    originalPrice: 1199,
  },
  {
    slug: "data-science",
    title: "Data Science & ML",
    description:
      "From statistics to machine learning — build real-world data pipelines, train models, and deploy them to production.",
    duration: "12 weeks",
    level: "Intermediate",
    color: "purple",
    price: 999,
    originalPrice: 1299,
  },
  {
    slug: "full-stack-web",
    title: "Full-Stack Web Development",
    description:
      "Build modern web applications with React, Node.js, databases, authentication, and deployment. End-to-end project-based learning.",
    duration: "14 weeks",
    level: "Beginner to Intermediate",
    color: "orange",
    price: 849,
    originalPrice: 1099,
  },
  {
    slug: "cybersecurity-fundamentals",
    title: "Cybersecurity Fundamentals",
    description:
      "Learn threat modeling, penetration testing, network security, and incident response. Build a security-first mindset for modern applications.",
    duration: "10 weeks",
    level: "Intermediate",
    color: "red",
    price: 949,
    originalPrice: 1249,
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    description:
      "Build cross-platform mobile apps with React Native. Cover navigation, state management, native APIs, and app store deployment.",
    duration: "12 weeks",
    level: "Intermediate",
    color: "teal",
    price: 879,
    originalPrice: 1149,
  },
  {
    slug: "ai-prompt-engineering",
    title: "AI & Prompt Engineering",
    description:
      "Master LLM integration, prompt design patterns, RAG architectures, fine-tuning, and building production AI applications.",
    duration: "6 weeks",
    level: "Beginner to Intermediate",
    color: "indigo",
    price: 699,
    originalPrice: 899,
  },
  {
    slug: "blockchain-web3",
    title: "Blockchain & Web3",
    description:
      "Understand smart contracts, Solidity, DeFi protocols, NFTs, and decentralized application architecture on Ethereum and beyond.",
    duration: "10 weeks",
    level: "Advanced",
    color: "yellow",
    price: 1099,
    originalPrice: 1399,
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    description:
      "Learn user research, wireframing, prototyping in Figma, design systems, accessibility, and user testing methodologies.",
    duration: "8 weeks",
    level: "Beginner",
    color: "pink",
    price: 649,
    originalPrice: 849,
  },
  {
    slug: "database-engineering",
    title: "Database Engineering",
    description:
      "Deep dive into PostgreSQL, MongoDB, Redis, query optimization, replication, sharding, and database architecture patterns.",
    duration: "8 weeks",
    level: "Intermediate to Advanced",
    color: "cyan",
    price: 849,
    originalPrice: 1099,
  },
  {
    slug: "system-design",
    title: "System Design & Architecture",
    description:
      "Learn to design scalable distributed systems — load balancers, message queues, caching layers, microservices, and CAP theorem in practice.",
    duration: "10 weeks",
    level: "Advanced",
    color: "slate",
    price: 1199,
    originalPrice: 1499,
  },
  {
    slug: "aws-solutions-architect",
    title: "AWS Solutions Architect",
    description:
      "Prepare for the AWS SAA certification. Cover EC2, S3, Lambda, VPC, IAM, RDS, CloudFormation, and real-world architecture patterns.",
    duration: "12 weeks",
    level: "Intermediate",
    color: "amber",
    price: 999,
    originalPrice: 1299,
  },
  {
    slug: "data-analytics-power-bi",
    title: "Data Analytics with Power BI",
    description:
      "Transform raw data into insights. Learn DAX, data modeling, dashboard design, ETL pipelines, and storytelling with data.",
    duration: "6 weeks",
    level: "Beginner",
    color: "lime",
    price: 599,
    originalPrice: 799,
  },
  {
    slug: "java-spring-boot",
    title: "Java & Spring Boot",
    description:
      "Build enterprise-grade APIs with Java 21 and Spring Boot. Cover REST, JPA, security, testing, and microservices deployment.",
    duration: "14 weeks",
    level: "Intermediate",
    color: "rose",
    price: 899,
    originalPrice: 1199,
  },
];
